### ISSUE TITLE
On Build: `unable to execute command: Executable "" doesn't exist!`

### ISSUE THREAD

**Issue by CWSpear** [sindresorhus/pwuid#3]
Tried on Node `4.1.2`, `4.0.0`, `0.10.40` and the results all appear to be the same. I'm pretty sure I have the toolchain all set up correct (from their docs, the `node-gyp --python /path/to/python2.7` doesn't really do anything, but otherwise...):

I'm not convinced it's a "you" problem, but `npm` wants to blame you, and I can't figure it out, so here I am... =/

(I'm on a Mac, El Capitan)

```
❯❯❯ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix

❯❯❯ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

❯❯❯ node-gyp --version
v3.0.3

❯❯❯ where python2.7
/usr/bin/python2.7

❯❯❯ npm config get python
/usr/bin/python2.7

# this is weird, but one of the steps it says to do for the toolchain, but doesn't seem to work?
❯❯❯ node-gyp --python `npm config get python`

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `make` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates a Makefile for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@3.0.3  /usr/local/lib/node_modules/node-gyp
node@4.1.2

❯❯❯ rm -Rf node_modules

❯❯❯ npm i
npm WARN package.json hudo@1.0.0 No repository field.
npm WARN package.json hudo@1.0.0 No README data

> pwuid@1.0.2 install /Users/cameron/Sites/github.cam/hudo/node_modules/pwuid
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/binding.o
error: unable to execute command: Executable "" doesn't exist!
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cameron/Sites/github.cam/hudo/node_modules/pwuid
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> fsevents@1.0.2 install /Users/cameron/Sites/github.cam/hudo/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/cameron/Sites/github.cam/hudo/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! pwuid@1.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwuid@1.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pwuid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pwuid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cameron/Sites/github.cam/hudo/npm-debug.log
```

**Comment by sindresorhus** [comment]
Should be fixed in 1.1.0 ;)

**Comment by CWSpear** [comment]
Hmm... still getting the error =(

```
> pwuid@1.1.0 install /Users/cameron/Sites/github.cam/hudo/node_modules/pwuid
> node-gyp rebuild

  CXX(target) Release/obj.target/binding/binding.o
error: unable to execute command: Executable "" doesn't exist!
make: *** [Release/obj.target/binding/binding.o] Error 1
```

Is there something else I may be missing?

**Comment by sindresorhus** [comment]
No idea. It now works for me on OS X and Ubuntu. Maybe try opening an issue in `node-gyp`.

**Comment by CWSpear** [comment]
I opened an issue here: https://github.com/nodejs/node-gyp/issues/764
